site_name: 网络之路
site_author: renjiangzhou@163.com

# 导航栏
nav:
  - 主页: index.md
  - 云上网络:
    - 华为云:
      - 虚拟私有云 VPC:
        - 图解虚拟私有云: 云上网络/华为云/虚拟私有云 VPC/001-图解虚拟私有云.md
        - 什么是虚拟私有云: 云上网络/华为云/虚拟私有云 VPC/002-什么是虚拟私有云.md
        - 产品优势: 云上网络/华为云/虚拟私有云 VPC/003-产品优势.md
        - "云上网络/华为云/虚拟私有云 VPC/云专线接入方案介绍.md"
  - 网络SOP:
    - 配置规范: 
      - 概要: 网络SOP/配置规范/000-说明.md
      - 1 基础配置: 
        - 配置用户登录的配置规范: 网络SOP/配置规范/01 基础配置/配置用户登录的配置规范.md
      - 2 系统管理: 
        - NTP: 网络SOP/配置规范/02 系统管理/NTP.md
        - NQA: 网络SOP/配置规范/02 系统管理/NQA.md
      - 3 可靠性: 
        - VRRP的配置规范: 网络SOP/配置规范/03 可靠性/VRRP的配置规范.md
        - BFD的配置规范: 网络SOP/配置规范/03 可靠性/BFD的配置规范.md
        - 多机备份的配置规范: 网络SOP/配置规范/03 可靠性/多机备份的配置规范.md
      - 4 接口管理: 
        - 网络SOP/配置规范/004-接口管理.md
  - 博客建设:
    - 官方文档参考: 博客建设/001-官方文档.md
    - 标题加粗样式: 博客建设/002-标题加粗样式.md
  # - 云上网络:
  #   - 华为云:
  #     - 虚拟私有云 VPC:
  #       - 产品介绍:
  #         - 图解虚拟私有云: 云上网络/华为云/虚拟私有云 VPC/001-图解虚拟私有云.md
  #         - 什么是虚拟私有云: 云上网络/华为云/虚拟私有云 VPC/002-什么是虚拟私有云.md
  #         - 产品优势: 云上网络/华为云/虚拟私有云 VPC/003-产品优势.md
  #         - "云上网络/华为云/虚拟私有云 VPC/云专线接入方案介绍.md"
  #     - 弹性公网IP EIP:
  #       - 产品介绍:
  #         - "云上网络/华为云/弹性公网IP EIP/002-什么是弹性公网IP.md"
  #   - 微软云:
  #     - 虚拟机:
  #       - Azure上的Red Hat Enterprise Linux映像: 云上网络/微软云/虚拟机/Azure上的Red Hat Enterprise Linux映像.md

#   - 管理: 
#     - 招聘:
#       - 实习生面试: 实习生面试.md
#   # - 广域网:
#   #   - BGP:
#   #     - BGP基础: 广域网/BGP/BGP基础.md
#   #   - OSPF:
#   #     - OSPF基础: 广域网/OSPF/OSPF基础.md

theme:    # 主题
  name: material    # 名称
  language: zh    # 语言，可设置多套切换
  # feature:
  #   tabs: true

  highlightjs: true    # JavaScript库在代码块中突出显示源代码。 默认值：True。
  hljs_languages:    # 默认情况下，highlight.js仅支持23种常用语言。在此列出额外需要支持的语言。
    - yaml
    - rust
  features:    # 导航
    - navigation.instant    # 即时加载
    - navigation.tracking    # 锚点跟踪
    - navigation.tabs     # 导航选项卡
    - navigation.tabs.sticky    # 粘性导航选项卡
    - navigation.sections   # 次级目录在侧边栏中呈现为组，与tabs同存则有2级导航

extra_css:
  - stylesheets/extra.css

markdown_extensions:  #推荐配置Markdown基本语法及其扩展
  - toc:    # 目录
      toc_depth: 6    # 目录深度，默认6，0则隐藏
      permalink: true

  - attr_list    # 属性列表扩展允许使用特殊语法将 HTML 属性和 CSS 类添加到几乎每个Markdown 内联和块级元素。
  - md_in_html    # Markdown in HTML扩展允许在 HTML 内部编写 Markdown，这对于使用自定义元素包装 Markdown 内容非常有用。

  - admonition    # 警告或标注
  - pymdownx.details    # 细节折叠
  - pymdownx.superfences    # 超级围栏

  - tables    # 启用 Markdown 表格支持，默认启用

#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true

#   - abbr    # 缩写或名词
#   - pymdownx.snippets  #片段，将任意文件或部分内容嵌入到文档中  


#   - def_list   #定义列表
#   - footnotes  #行内脚注
#   - meta   #元数据

#   - pymdownx.arithmatex:  # 数学公式
#       generic: true  
#   - pymdownx.betterem:   #粗体斜体
#       smart_enable: all
#   - pymdownx.highlight    # 代码高亮，对代码块（SuperFences）和行内代码块（InlineHilite）的语法突出显示
#   - pymdownx.inlinehilite   # 行内高亮
#   - pymdownx.smartsymbols   # 智能符号
#   - pymdownx.tabbed:    # 内容选项卡
#       alternate_style: true   # 启用内容选项卡替代样式，必须开启
#   - pymdownx.tasklist:    # 任务列表
#       custom_checkbox: true   # 切换复选框的呈现样式，将原生复选框样式替换为漂亮的图标

# extra_javascript:
#   - javascripts/baidu-tongji.js  #百度统计
#   - javascripts/mathjax.js  #数学公式的JS
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - glightbox:    # glightbox插件,可以为您的文档添加图像缩放功能，
      width: 100%    # 
      height: auto    # 
      zoomable: true    # 
      draggable: true    # 
      closeButton: true    # 
      closeOnOutsideClick: true    # 